#!/bin/zsh

#########################################
#      EXPORT ENVIRONMENT VARIABLE      #
#########################################

export TERM='termite'
export DOTFILES="$HOME/dotfiles"

# XDG

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# editor

export EDITOR="vim"
export VISUAL="vim"

# zsh

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# go

export GOPATH="$HOME/.go"

# paths
PATH=$PATH:$GOPATH/bin:$HOME/.local/bin
